import type {
  ReportCatalogEntity,
  ReportEntityKey,
  ReportFieldDefinition,
  ReportFilterOperator,
} from '@amateur/shared-types';

/**
 * Reportable Field Catalog
 * ------------------------
 * Single source of truth describing which fields are filterable, selectable,
 * sortable, and exportable across the reporting v1 entities.
 *
 * Adding a new reportable field is intentionally a single-file change:
 *   1. add the field definition below,
 *   2. add a SQL projection in `query-compiler.ts` if the row should display it,
 *   3. add a join descriptor in `relations.ts` if it spans relations.
 */

const TEXT_OPS: ReportFilterOperator[] = [
  'is',
  'isNot',
  'contains',
  'notContains',
  'startsWith',
  'endsWith',
  'isEmpty',
  'isNotEmpty',
];

const ENUM_OPS: ReportFilterOperator[] = ['is', 'isNot', 'in', 'notIn', 'isEmpty', 'isNotEmpty'];
const DATE_OPS: ReportFilterOperator[] = ['is', 'isNot', 'gt', 'gte', 'lt', 'lte', 'between', 'isEmpty', 'isNotEmpty'];
const NUMBER_OPS: ReportFilterOperator[] = ['is', 'isNot', 'gt', 'gte', 'lt', 'lte', 'between', 'isEmpty', 'isNotEmpty'];
const BOOL_OPS: ReportFilterOperator[] = ['is', 'isNot'];
const REL_OPS: ReportFilterOperator[] = ['exists', 'notExists'];

const ATHLETE_STATUS_OPTIONS = (['trial', 'active', 'paused', 'inactive', 'archived'] as const).map((value) => ({
  value,
  labelKey: `app.enums.athleteStatus.${value}`,
}));

const ATHLETE_GENDER_OPTIONS = (['female', 'male', 'non_binary', 'unspecified'] as const).map((value) => ({
  value,
  labelKey: `pages.athletes.genders.${value}`,
}));

const CHARGE_STATUS_OPTIONS = (['pending', 'partially_paid', 'paid', 'cancelled'] as const).map((value) => ({
  value,
  labelKey: `app.enums.athleteChargeStatus.${value}`,
}));

const LESSON_STATUS_OPTIONS = (['planned', 'completed', 'cancelled'] as const).map((value) => ({
  value,
  labelKey: `app.enums.trainingStatus.${value}`,
}));

const ATTENDANCE_OPTIONS = (['present', 'absent', 'excused', 'late'] as const).map((value) => ({
  value,
  labelKey: `app.enums.attendanceStatus.${value}`,
}));

const ATHLETES: ReportFieldDefinition[] = [
  {
    key: 'athlete.firstName',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.firstName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'athlete.lastName',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.lastName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'athlete.preferredName',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.preferredName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'athlete.gender',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.gender',
    type: 'enum',
    operators: ENUM_OPS,
    options: ATHLETE_GENDER_OPTIONS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.shirtSize',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.shirtSize',
    type: 'enum',
    operators: ENUM_OPS,
    options: [
      { value: 'XS', label: 'XS' },
      { value: 'S', label: 'S' },
      { value: 'M', label: 'M' },
      { value: 'L', label: 'L' },
      { value: 'XL', label: 'XL' },
      { value: 'XXL', label: 'XXL' },
    ],
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.status',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.status',
    type: 'enum',
    operators: ENUM_OPS,
    options: ATHLETE_STATUS_OPTIONS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.birthDate',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.birthDate',
    type: 'date',
    operators: DATE_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.birthYear',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.birthYear',
    type: 'number',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.jerseyNumber',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.jerseyNumber',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'athlete.sportBranchName',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.sportBranch',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.primaryGroupName',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.primaryGroup',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.primaryGroupId',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.primaryGroupId',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn', 'isEmpty', 'isNotEmpty'],
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'athlete.teamId',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.teamId',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn'],
    selectable: false,
    sortable: false,
    exportable: false,
    hintKey: 'pages.reports.fields.athlete.teamIdHint',
  },
  {
    key: 'athlete.guardiansExist',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.guardiansExist',
    type: 'boolean',
    operators: REL_OPS,
    relationCheck: true,
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'athlete.privateLessonsExist',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.privateLessonsExist',
    type: 'boolean',
    operators: REL_OPS,
    relationCheck: true,
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'athlete.unpaidChargesExist',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.unpaidChargesExist',
    type: 'boolean',
    operators: REL_OPS,
    relationCheck: true,
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'athlete.unpaidPrivateLessonChargesExist',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.unpaidPrivateLessonChargesExist',
    type: 'boolean',
    operators: REL_OPS,
    relationCheck: true,
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'athlete.outstandingTotal',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.outstandingTotal',
    type: 'currency',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.guardianCount',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.guardianCount',
    type: 'number',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.teamCount',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.teamCount',
    type: 'number',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'athlete.id',
    entity: 'athletes',
    labelKey: 'pages.reports.fields.athlete.id',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn'],
    selectable: false,
    sortable: false,
    exportable: false,
  },
];

const GUARDIANS: ReportFieldDefinition[] = [
  {
    key: 'guardian.firstName',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.firstName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'guardian.lastName',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.lastName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'guardian.email',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.email',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'guardian.phone',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.phone',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'guardian.athleteCount',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.athleteCount',
    type: 'number',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'guardian.athletesExist',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.athletesExist',
    type: 'boolean',
    operators: REL_OPS,
    relationCheck: true,
    selectable: false,
    sortable: false,
    exportable: false,
  },
  {
    key: 'guardian.contactComplete',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.contactComplete',
    type: 'boolean',
    operators: BOOL_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'guardian.id',
    entity: 'guardians',
    labelKey: 'pages.reports.fields.guardian.id',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn'],
    selectable: false,
    sortable: false,
    exportable: false,
  },
];

const PRIVATE_LESSONS: ReportFieldDefinition[] = [
  {
    key: 'lesson.athleteName',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.athleteName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'lesson.coachName',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.coachName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'lesson.scheduledStart',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.scheduledStart',
    type: 'datetime',
    operators: DATE_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'lesson.status',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.status',
    type: 'enum',
    operators: ENUM_OPS,
    options: LESSON_STATUS_OPTIONS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'lesson.attendanceStatus',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.attendanceStatus',
    type: 'enum',
    operators: ENUM_OPS,
    options: ATTENDANCE_OPTIONS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'lesson.focus',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.focus',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'lesson.location',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.location',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'lesson.chargeStatus',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.chargeStatus',
    type: 'enum',
    operators: ENUM_OPS,
    options: [
      { value: 'unbilled', labelKey: 'pages.reports.values.unbilled' },
      ...CHARGE_STATUS_OPTIONS,
    ],
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'lesson.chargeOverdue',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.chargeOverdue',
    type: 'boolean',
    operators: BOOL_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'lesson.chargeRemaining',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.chargeRemaining',
    type: 'currency',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'lesson.id',
    entity: 'private_lessons',
    labelKey: 'pages.reports.fields.lesson.id',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn'],
    selectable: false,
    sortable: false,
    exportable: false,
  },
];

const FINANCE: ReportFieldDefinition[] = [
  {
    key: 'charge.athleteName',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.athleteName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'charge.itemName',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.itemName',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
    quickSearch: true,
  },
  {
    key: 'charge.itemCategory',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.itemCategory',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.amount',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.amount',
    type: 'currency',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.allocatedAmount',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.allocatedAmount',
    type: 'currency',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.remainingAmount',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.remainingAmount',
    type: 'currency',
    operators: NUMBER_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.dueDate',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.dueDate',
    type: 'date',
    operators: DATE_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.derivedStatus',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.status',
    type: 'enum',
    operators: ENUM_OPS,
    options: CHARGE_STATUS_OPTIONS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.isOverdue',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.isOverdue',
    type: 'boolean',
    operators: BOOL_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'charge.fromPrivateLesson',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.fromPrivateLesson',
    type: 'boolean',
    operators: BOOL_OPS,
    selectable: true,
    sortable: false,
    exportable: true,
  },
  {
    key: 'charge.billingPeriodLabel',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.billingPeriodLabel',
    type: 'string',
    operators: TEXT_OPS,
    selectable: true,
    sortable: true,
    exportable: true,
  },
  {
    key: 'charge.id',
    entity: 'finance_charges',
    labelKey: 'pages.reports.fields.charge.id',
    type: 'uuid',
    operators: ['is', 'isNot', 'in', 'notIn'],
    selectable: false,
    sortable: false,
    exportable: false,
  },
];

const REPORT_CATALOG: Record<ReportEntityKey, ReportCatalogEntity> = {
  athletes: {
    key: 'athletes',
    labelKey: 'pages.reports.entities.athletes',
    defaultColumns: [
      'athlete.lastName',
      'athlete.firstName',
      'athlete.gender',
      'athlete.shirtSize',
      'athlete.primaryGroupName',
      'athlete.status',
      'athlete.outstandingTotal',
    ],
    defaultSort: { field: 'athlete.lastName', direction: 'asc' },
    exportRowLimit: 5000,
    fields: ATHLETES,
  },
  guardians: {
    key: 'guardians',
    labelKey: 'pages.reports.entities.guardians',
    defaultColumns: [
      'guardian.lastName',
      'guardian.firstName',
      'guardian.email',
      'guardian.phone',
      'guardian.athleteCount',
      'guardian.contactComplete',
    ],
    defaultSort: { field: 'guardian.lastName', direction: 'asc' },
    exportRowLimit: 5000,
    fields: GUARDIANS,
  },
  private_lessons: {
    key: 'private_lessons',
    labelKey: 'pages.reports.entities.privateLessons',
    defaultColumns: [
      'lesson.scheduledStart',
      'lesson.athleteName',
      'lesson.coachName',
      'lesson.status',
      'lesson.chargeStatus',
      'lesson.chargeRemaining',
    ],
    defaultSort: { field: 'lesson.scheduledStart', direction: 'asc' },
    exportRowLimit: 5000,
    fields: PRIVATE_LESSONS,
  },
  finance_charges: {
    key: 'finance_charges',
    labelKey: 'pages.reports.entities.finance',
    defaultColumns: [
      'charge.dueDate',
      'charge.athleteName',
      'charge.itemName',
      'charge.amount',
      'charge.remainingAmount',
      'charge.derivedStatus',
      'charge.isOverdue',
    ],
    defaultSort: { field: 'charge.dueDate', direction: 'asc' },
    exportRowLimit: 5000,
    fields: FINANCE,
  },
};

export function listCatalogEntities(): ReportCatalogEntity[] {
  return (Object.values(REPORT_CATALOG) as ReportCatalogEntity[]).map((entity) => ({
    ...entity,
    fields: entity.fields.map((field) => ({ ...field })),
  }));
}

export function getCatalogEntity(entity: ReportEntityKey): ReportCatalogEntity | null {
  const found = REPORT_CATALOG[entity];
  if (!found) return null;
  return { ...found, fields: found.fields.map((field) => ({ ...field })) };
}

export function getFieldDefinition(entity: ReportEntityKey, key: string): ReportFieldDefinition | null {
  const found = REPORT_CATALOG[entity]?.fields.find((field) => field.key === key);
  return found ? { ...found } : null;
}

export const REPORT_ENTITY_KEYS: ReportEntityKey[] = ['athletes', 'guardians', 'private_lessons', 'finance_charges'];
